### ISSUE TITLE
What is this.clickStartShape?

### ISSUE THREAD

**Issue by GitHubish** [SujalShah3234/White-Board#1]
This property does not seem to be defined in the component and in the service.

**Comment by SujalShah3234** [comment]
You can find more details here: https://github.com/konvajs/konva/issues/318
This issue is causing maybe because of you're using latest konva.js version 8.2.1
Use konva.js version ^7.2.2
I've updated my repo and it's working for now.
I'll complete the migration process of konva.js soon.
